/**
 * Multi-agent discussion types and mock orchestration.
 * In production, each message would be generated by an LLM with the advisor's instructions.
 */

import { ADVISOR_IDS, type AdvisorId } from "./advisors";

export type MessageRole = "advisor" | "system";

export interface DiscussionMessage {
  id: string;
  advisorId: string; // built-in AdvisorId or custom id
  role: MessageRole;
  content: string;
  timestamp: string;
  isPro?: boolean; // pro for the stock vs con
}

export interface DiscussionState {
  stockSymbol: string;
  messages: DiscussionMessage[];
  status: "idle" | "discussing" | "done";
}

const MOCK_CONTENT: Record<AdvisorId, (symbol: string) => string> = {
  buffett: (symbol) =>
    `I'd look at ${symbol} the same way I look at any business: does it have a durable moat and predictable earnings? If the numbers show consistent returns on equity and a sensible price relative to that, it could be a candidate for the portfolio. I'm not interested in what the news says this week—I care about where the business will be in 10 years.`,
  lynch: (symbol) =>
    `The key is whether ${symbol} is a growth story that's still reasonably priced. Check the PEG ratio and same-store sales or equivalent. If you've seen the product or service in your daily life and it's winning, that's a good start. Sentiment can be noisy—focus on whether the fundamentals support the narrative.`,
  dalio: (symbol) =>
    `Where does ${symbol} sit in the economic cycle and in a diversified portfolio? If it's highly correlated to growth and risk-on sentiment, you need to size it so that a drawdown doesn't blow up your plan. I'd want to see how it behaves in different macro regimes before committing.`,
  graham: (symbol) =>
    `Unless there's a clear margin of safety—meaning the price is well below a conservative estimate of value—I'd be cautious. Check the balance sheet: debt levels, current ratio, and whether earnings are stable. Mr. Market's current mood (sentiment) is not a substitute for that discipline.`,
  wood: (symbol) =>
    `If ${symbol} is in a space that's being transformed by innovation—whether AI, genomics, or automation—today's valuation might not reflect the 5-year opportunity. I'm willing to pay for growth when the TAM is expanding and the company has a clear path to capture it. Short-term sentiment often underweights disruption.`,
};

const MOCK_PRO: Record<AdvisorId, boolean> = {
  buffett: true,
  lynch: true,
  dalio: false,
  graham: false,
  wood: true,
};

const FALLBACK_MOCK = (symbol: string) =>
  `Considering ${symbol}, I'd weigh the fundamentals and current sentiment. Diversification and a margin of safety matter.`;

/** Mock discussion for hackathon. Replace with LLM calls using advisor instructions + context. */
export function generateMockDiscussion(
  symbol: string,
  sentimentSummary: { currentSentiment: number; outperformRate: number },
  advisorIds: string[] = ADVISOR_IDS
): DiscussionMessage[] {
  const ts = () => new Date().toISOString();
  return advisorIds.map((advisorId, i) => {
    const contentFn = MOCK_CONTENT[advisorId as AdvisorId];
    const isPro = MOCK_PRO[advisorId as AdvisorId];
    return {
      id: String(i + 1),
      advisorId,
      role: "advisor" as const,
      content: contentFn ? contentFn(symbol) : FALLBACK_MOCK(symbol),
      timestamp: ts(),
      isPro: typeof isPro === "boolean" ? isPro : true,
    };
  });
}
