/**
 * Multi-agent discussion types and mock orchestration.
 * In production, each message would be generated by an LLM with the advisor's instructions.
 */

import { ADVISOR_IDS, type AdvisorId } from "./advisors";

export type MessageRole = "advisor" | "system";

export interface DiscussionMessage {
  id: string;
  advisorId: string; // built-in AdvisorId or custom id
  role: MessageRole;
  content: string;
  timestamp: string;
  isPro?: boolean; // pro for the stock vs con
}

type MockContext = {
  symbol: string;
  sentiment: number;
  outperformRate: number;
  headline?: string;
};

const MOCK_CONTENT: Record<AdvisorId, (ctx: MockContext) => string> = {
  buffett: (ctx) => {
    const lead = ctx.headline
      ? `Given the recent news that ${ctx.headline}, I'd still look at ${ctx.symbol} the same way I look at any business: `
      : `I'd look at ${ctx.symbol} the same way I look at any business: `;
    return `${lead}does it have a durable moat and predictable earnings? With sentiment around ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate, the key is whether the numbers show consistent returns on equity and a sensible price. I care about where the business will be in 10 years.`;
  },
  lynch: (ctx) => {
    const lead = ctx.headline
      ? `The recent headline about ${ctx.symbol}—"${ctx.headline.slice(0, 50)}${ctx.headline.length > 50 ? "…" : ""}"—is noise unless the growth story is still reasonably priced. `
      : "";
    return `${lead}The key is whether ${ctx.symbol} is a growth story that's still reasonably priced. Sentiment at ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate: check the PEG and whether the fundamentals support the narrative.`;
  },
  dalio: (ctx) =>
    `Where does ${ctx.symbol} sit in the economic cycle? With sentiment ${ctx.sentiment.toFixed(2)} and a ${ctx.outperformRate}% outperform rate, I'd want to see how it behaves in different macro regimes. Size it so a drawdown doesn't blow up your plan.`,
  graham: (ctx) =>
    `For ${ctx.symbol}, sentiment is ${ctx.sentiment.toFixed(2)} and outperform rate ${ctx.outperformRate}%. Unless there's a clear margin of safety—price well below a conservative estimate of value—I'd be cautious. Check the balance sheet; Mr. Market's mood is not a substitute for that discipline.`,
  wood: (ctx) =>
    `If ${ctx.symbol} is in a space being transformed by innovation, today's valuation may not reflect the 5-year opportunity. With sentiment at ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate, I'm willing to pay for growth when the TAM is expanding and the company has a clear path to capture it.`,
  munger: (ctx) =>
    `For ${ctx.symbol}, invert first: what would make this a bad investment? With sentiment ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate, the question is whether the business is wonderful and the price fair. Avoid stupidity; stay in your circle of competence.`,
  marks: (ctx) =>
    `Where are we in the cycle for ${ctx.symbol}? Sentiment ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate—second-level thinking says: what is the crowd missing? The best opportunities appear when others are fearful. Control risk and demand a margin of safety.`,
  bogle: (ctx) =>
    `For ${ctx.symbol}, ask: does picking this stock beat the market after costs? Sentiment ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate are noise for the long-term holder. Most investors are better off in a low-cost index; if you own this name, keep it simple and disciplined.`,
  soros: (ctx) =>
    `The dominant bias around ${ctx.symbol}—sentiment ${ctx.sentiment.toFixed(2)}, ${ctx.outperformRate}% outperform rate—can be reflexive. Perceptions affect fundamentals. Look for inflection points and macro context; size the position by conviction.`,
  klarman: (ctx) =>
    `For ${ctx.symbol}, is there a margin of safety? Sentiment ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate suggest how the crowd is positioned. Value is the marriage of contrarian thinking and a calculator; avoid permanent loss of capital.`,
};

const MOCK_PRO: Record<AdvisorId, boolean> = {
  buffett: true,
  lynch: true,
  dalio: false,
  graham: false,
  wood: true,
  munger: true,
  marks: false,
  bogle: false,
  soros: true,
  klarman: false,
};

const FALLBACK_MOCK = (ctx: MockContext) =>
  `Considering ${ctx.symbol} with sentiment ${ctx.sentiment.toFixed(2)} and ${ctx.outperformRate}% outperform rate, I'd weigh the fundamentals. Diversification and a margin of safety matter.`;

/** Mock discussion when Gemini is unavailable. Uses sentiment/headlines so each stock gets different text. */
export function generateMockDiscussion(
  symbol: string,
  sentimentSummary: { currentSentiment: number; outperformRate: number; recentHeadlines?: { text: string }[] },
  advisorIds: string[] = ADVISOR_IDS
): DiscussionMessage[] {
  const headline = sentimentSummary.recentHeadlines?.[0]?.text;
  const ctx: MockContext = {
    symbol,
    sentiment: sentimentSummary.currentSentiment,
    outperformRate: sentimentSummary.outperformRate,
    headline,
  };
  const ts = () => new Date().toISOString();
  return advisorIds.map((advisorId, i) => {
    const contentFn = MOCK_CONTENT[advisorId as AdvisorId];
    const isPro = MOCK_PRO[advisorId as AdvisorId];
    return {
      id: String(i + 1),
      advisorId,
      role: "advisor" as const,
      content: contentFn ? contentFn(ctx) : FALLBACK_MOCK(ctx),
      timestamp: ts(),
      isPro: typeof isPro === "boolean" ? isPro : true,
    };
  });
}
